import '../models/memberprofile_model.dart';
import '../models/feed_model.dart';

List<MemberProfileModel>memberprofile=[
  MemberProfileModel(
  id: 1, 
  imagesmUrl: "assets/images/Emily.png", 
  imagebgUrl: "assets/images/Emily_bg.png", 
  fullname: "Emily Williams", 
  gender: "Female", 
  position: "Organizer", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 2, 
  imagesmUrl: "assets/images/Ryan.png", 
  imagebgUrl: "assets/images/Ryan_bg.png", 
  fullname: "Ryan Johnson", 
  gender: "Male", 
  position: "Poacher", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 3, 
  imagesmUrl: "assets/images/Brandon.png", 
  imagebgUrl: "assets/images/Brandon_bg.png", 
  fullname: "Brandom Mitchell", 
  gender: "Male", 
  position: "Gardener", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 4, 
  imagesmUrl: "assets/images/Jessica.png", 
  imagebgUrl: "assets/images/Jessica_bg.png", 
  fullname: "Jessica Taylor", 
  gender: "Female", 
  position: "Blogger", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 5, 
  imagesmUrl: "assets/images/Samantha.png", 
  imagebgUrl: "assets/images/Samantha_bg.png", 
  fullname: "Samantha Johnson", 
  gender: "Female", 
  position: "Developer", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 6, 
  imagesmUrl: "assets/images/Ashley.png", 
  imagebgUrl: "assets/images/Ashley_bg.png", 
  fullname: "Ashley Martinez", 
  gender: "Female", 
  position: "Supervisor", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 7, 
  imagesmUrl: "assets/images/Olivia.png", 
  imagebgUrl: "assets/images/Olivia_bg.png", 
  fullname: "Olivia Brown", 
  gender: "Female", 
  position: "Content Creator", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 8, 
  imagesmUrl: "assets/images/Tyler.png", 
  imagebgUrl: "assets/images/Tyler_bg.png", 
  fullname: "Tyler Davis", 
  gender: "Male", 
  position: "Developer", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 9, 
  imagesmUrl: "assets/images/Kevin.png", 
  imagebgUrl: "assets/images/Kevin_bg.png", 
  fullname: "Kevin Anderson", 
  gender: "Male", 
  position: "Business Man", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 10, 
  imagesmUrl: "assets/images/Dylan.png", 
  imagebgUrl: "assets/images/Dylan_bg.png", 
  fullname: "Dylan Thompson", 
  gender: "Male", 
  position: "Producer", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 11, 
  imagesmUrl: "assets/images/Nathan.png", 
  imagebgUrl: "assets/images/Nathan_bg.png", 
  fullname: "Nathan Evans", 
  gender: "Male", 
  position: "Director", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 12, 
  imagesmUrl: "assets/images/Mike.png", 
  imagebgUrl: "assets/images/Mike_bg.png", 
  fullname: "Mike Nolan", 
  gender: "Male", 
  position: "Photographer", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
  MemberProfileModel(
  id: 13, 
  imagesmUrl: "assets/images/Jude.png", 
  imagebgUrl: "assets/images/Jude_bg.png", 
  fullname: "Jude Potter", 
  gender: "Female", 
  position: "Doctor", 
  contact: "+23300000000", 
  bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec aliquet sed velit a pulvinar. Pellentesque feugiat at nulla at placerat. Morbi ac felis dui. Duis accumsan quis risus vitae faucibus. Sed ut tellus risus. Donec semper purus iaculis, hendrerit elit vitae, lobortis lacus. Cras bibendum, eros eu elementum placerat, elit leo interdum erat, ac congue massa nibh id est. Pellentesque lacinia maximus tortor dapibus tempus. Nullam at pellentesque nisi. Phasellus id justo et nisi vestibulum lacinia ut et elit. Integer at urna dui. Mauris vel egestas eros.",
  ),
];


List<FeedModel>feedmodel=[
  FeedModel(
    id: 1, 
    profileImg: "assets/images/Jude.png", 
    username: "Jude Potter", 
    caption: "Standing Pokuase Interchange", 
    time: "1h", 
    postImg: "assets/images/Pokuase_interchange.jpg", 
    likecount: 2, 
    mutualFriendImg1: "https://picsum.photos/300/300/?boy", 
    mutualFriendImg2: "https://picsum.photos/300/300/?girl",
    liked:false,
    ),
  FeedModel(
    id: 2, 
    profileImg: "assets/images/Mike.png", 
    username: "Mike Nolan", 
    caption: "Ongoing Kath Hospital Maturnity Block", 
    time: "2h", 
    postImg: "assets/images/kath_maturnityblock.jpg", 
    likecount: 2, 
    mutualFriendImg1: "https://picsum.photos/300/300/?boy", 
    mutualFriendImg2: "https://picsum.photos/300/300/?girl",
    liked: false
    ),
  FeedModel(
    id: 3, 
    profileImg: "assets/images/Nathan.png", 
    username: "Nathan Evans", 
    caption: "Fully Completed Affordable housing project in Kumasi", 
    time: "3h", 
    postImg: "assets/images/affordable_housing.jpg", 
    likecount: 2, 
    mutualFriendImg1: "https://picsum.photos/300/300/?boy", 
    mutualFriendImg2: "https://picsum.photos/300/300/?girl",
    liked: false
    ),
  FeedModel(
    id: 4, 
    profileImg: "assets/images/Dylan.png", 
    username: "Dylan Thompson", 
    caption: "New Prempeh I International Airport", 
    time: "3h", 
    postImg: "assets/images/kumasi_airport.jpg", 
    likecount: 2, 
    mutualFriendImg1: "https://picsum.photos/300/300/?boy", 
    mutualFriendImg2: "https://picsum.photos/300/300/?girl",
    liked: false
    ),
];